pipeline {
  agent any

  tools {
    terraform 'terraform'
  }

  parameters {
    booleanParam(name: 'DESTROY', defaultValue: false, description: 'Enable destroy stage')
  }

  stages {
    stage('Init & Validate') {
      steps {
        dir('infra-aws') {
          sh 'terraform init -upgrade'
          sh 'terraform validate'
        }
      }
    }

     stage('Plan') {
      steps {
        withCredentials([string(credentialsId: 'google-api-key', variable: 'GOOGLE_API_KEY')]) {
          dir('infra-aws') {
            sh 'terraform plan -var="google_api_key=${GOOGLE_API_KEY}" -out=tfplan'
          }
          archiveArtifacts artifacts: 'infra-aws/tfplan'
        }
      }
    }

    stage('Apply') {
      steps {
        withCredentials([string(credentialsId: 'google-api-key', variable: 'GOOGLE_API_KEY')]) {
          dir('infra-aws') {
            sh 'terraform apply -auto-approve -var="google_api_key=${GOOGLE_API_KEY}" tfplan'
          }
        }
      }
    }

    stage('Destroy') {
      when { expression { params.DESTROY } }
      steps {
        withCredentials([string(credentialsId: 'google-api-key', variable: 'GOOGLE_API_KEY')]) {
          dir('infra-aws') {
            sh 'terraform destroy -auto-approve -var="google_api_key=${GOOGLE_API_KEY}"'
          }
        }
      }
    }
  }
}
