# Generated by Django 5.2.1 on 2025-06-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_place_id_alter_review_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='review',
            name='restaurant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
